<?php

namespace Database\Seeders;

use App\Models\Program;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProgramSeeder extends Seeder
{

    protected $programs = [
        'Радио NS',
        'Европа плюс Казахстан',
        'Русское радио Азия',
        'Love Radio',
        'Авторадио Казахстан',
        'Жулдыз FM',
        'Той Думан Радиосы',
        'Народное радио',
        'Ретро FM Qazaqstan',
        'Energy FM',
        'Жана FM',
        'Радио Дача',
        'LUX FM',
        'Business FM',
        'BEU FM',
        'Той Думан радиосы регион',
        'Love Radio Астана',
        'ОРДА FM',
        'TALIM TV',
        'Той Думан',
        'CASPIAN NEWS',
        'Kоғам TV',
        'Jibek Joly',
        'НТК',
        'КТК',
        'МИР 24',
        'Астана',
        'Alatau',
        '31 канал',
        'Седьмой канал',
        'Almaty',
        'Тұран ТВ',
        'Atameken Business',
        'TALIM TV',
        'Gakku Media',
        'Той Думан',
        'MUZZONE',
        'MUNARA TV',
        'TDQ 42',
        'Новое телевидение',
        'Карачаганак',
        'Серик ТВ',
        'Рика ТВ',
        '77TV',
        'Taraz 24',
        'QARATAU TV',
        'HAN TV',
        'Айгак',
        'Отырар ТВ',
        'Elnur TV',
        'Туран - Туркестан',
        'САНҰР ТВ',
        'ART TV',
        'Сәт',
        'Акцент',
        'Алау ТВ',
        'ТВС',
        'Арка дидары',
        'Ирбис',
        'ЭГТ',
        'AQTAU',
        'Caspian News',
        'Первый Северный',
        'Муниципиалдық телеарна',
        'Первый Карагандинский',
        'Оркен-Media',
        'Ulytau',
        '5 канал',
        'Aqsham',
        'Qazaqstan',
        'Balapan',
        'Qazsport',
        'ABAI TV',
        'Хабар',
        'Хабар 24',
        'Ел Арна',
        'Jibek Joly',
        'Первый канал Евразия',
        'МИР',
        'Muzlife',
        'Q sport Extra',
        'KinoHIT',
        'KinoALEM',
        'Жетысу',
        'ALVA TV',
        'ТВК-6',
        'Жастар',
        'Дидар',
        'Твое ТВ',
        'Қоғам ТВ',
        'МТРК',
        'Turkistan',
        'Shymqala',
        'Фараб',
        '«KÓKSHE» ',
        '«AQTÓBE»',
        '«ATYRAÝ» ',
        '«ALTAI»',
        '«ATYRAÝ» ',
        '«SEMEI»',
        '«JAMBYL» ',
        '«AQJAIYQ»',
        '«SARYARQA» ',
        '«QOSTANAI»',
        '«QYZYLORDA»',
        '«MAŃǴYSTAÝ»',
        '«ERTIS» ',
        '«QYZYLJAR»',
        '«OŃTÚSTIK» ',
    ];
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $programs = collect($this->programs)->map(fn ($item) => ['name' => $item])->toArray();
        Program::upsert($programs, []);
    }
}
